# Copyright (C) 2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/bq/zeno/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/bq/zeno/proprietary/bin/kpoc_charger:system/bin/kpoc_charger \
    vendor/bq/zeno/proprietary/lib/hw/camera.mt8163.so:system/lib/hw/camera.mt8163.so \
    vendor/bq/zeno/proprietary/lib/libcam.camadapter.so:system/lib/libcam.camadapter.so \
    vendor/bq/zeno/proprietary/lib/libcam.campipe.so:system/lib/libcam.campipe.so \
    vendor/bq/zeno/proprietary/lib/libcam.camshot.so:system/lib/libcam.camshot.so \
    vendor/bq/zeno/proprietary/lib/libcam.device1.so:system/lib/libcam.device1.so \
    vendor/bq/zeno/proprietary/lib/libcam.device3.so:system/lib/libcam.device3.so \
    vendor/bq/zeno/proprietary/lib/libcam.exif.so:system/lib/libcam.exif.so \
    vendor/bq/zeno/proprietary/lib/libcam.exif.v3.so:system/lib/libcam.exif.v3.so \
    vendor/bq/zeno/proprietary/lib/libcam.hal3a.v3.so:system/lib/libcam.hal3a.v3.so \
    vendor/bq/zeno/proprietary/lib/libcam.halsensor.so:system/lib/libcam.halsensor.so \
    vendor/bq/zeno/proprietary/lib/libcam.iopipe.so:system/lib/libcam.iopipe.so \
    vendor/bq/zeno/proprietary/lib/libcam.iopipe_FrmB.so:system/lib/libcam.iopipe_FrmB.so \
    vendor/bq/zeno/proprietary/lib/libcam.metadata.so:system/lib/libcam.metadata.so \
    vendor/bq/zeno/proprietary/lib/libcam.metadataprovider.so:system/lib/libcam.metadataprovider.so \
    vendor/bq/zeno/proprietary/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
    vendor/bq/zeno/proprietary/lib/libcam.sdkclient.so:system/lib/libcam.sdkclient.so \
    vendor/bq/zeno/proprietary/lib/libcam.utils.so:system/lib/libcam.utils.so \
    vendor/bq/zeno/proprietary/lib/libcam1_utils.so:system/lib/libcam1_utils.so \
    vendor/bq/zeno/proprietary/lib/libcam3_app.so:system/lib/libcam3_app.so \
    vendor/bq/zeno/proprietary/lib/libcam3_hwnode.so:system/lib/libcam3_hwnode.so \
    vendor/bq/zeno/proprietary/lib/libcam3_hwpipeline.so:system/lib/libcam3_hwpipeline.so \
    vendor/bq/zeno/proprietary/lib/libcam3_pipeline.so:system/lib/libcam3_pipeline.so \
    vendor/bq/zeno/proprietary/lib/libcam3_utils.so:system/lib/libcam3_utils.so \
    vendor/bq/zeno/proprietary/lib/libcam_hwutils.so:system/lib/libcam_hwutils.so \
    vendor/bq/zeno/proprietary/lib/libcam_mmp.so:system/lib/libcam_mmp.so \
    vendor/bq/zeno/proprietary/lib/libcam_platform.so:system/lib/libcam_platform.so \
    vendor/bq/zeno/proprietary/lib/libcamalgo.so:system/lib/libcamalgo.so \
    vendor/bq/zeno/proprietary/lib/libcamdrv.so:system/lib/libcamdrv.so \
    vendor/bq/zeno/proprietary/lib/libcamdrv_FrmB.so:system/lib/libcamdrv_FrmB.so \
    vendor/bq/zeno/proprietary/lib/libcameracustom.so:system/lib/libcameracustom.so \
    vendor/bq/zeno/proprietary/lib/libmtkcamera_client.so:system/lib/libmtkcamera_client.so \
    vendor/bq/zeno/proprietary/lib/libshowlogo.so:system/lib/libshowlogo.so \
    vendor/bq/zeno/proprietary/lib/libtz_uree.so:system/lib/libtz_uree.so \
    vendor/bq/zeno/proprietary/lib64/hw/camera.mt8163.so:system/lib64/hw/camera.mt8163.so \
    vendor/bq/zeno/proprietary/lib64/libcam.camadapter.so:system/lib64/libcam.camadapter.so \
    vendor/bq/zeno/proprietary/lib64/libcam.campipe.so:system/lib64/libcam.campipe.so \
    vendor/bq/zeno/proprietary/lib64/libcam.camshot.so:system/lib64/libcam.camshot.so \
    vendor/bq/zeno/proprietary/lib64/libcam.device1.so:system/lib64/libcam.device1.so \
    vendor/bq/zeno/proprietary/lib64/libcam.device3.so:system/lib64/libcam.device3.so \
    vendor/bq/zeno/proprietary/lib64/libcam.exif.so:system/lib64/libcam.exif.so \
    vendor/bq/zeno/proprietary/lib64/libcam.exif.v3.so:system/lib64/libcam.exif.v3.so \
    vendor/bq/zeno/proprietary/lib64/libcam.hal3a.v3.so:system/lib64/libcam.hal3a.v3.so \
    vendor/bq/zeno/proprietary/lib64/libcam.halsensor.so:system/lib64/libcam.halsensor.so \
    vendor/bq/zeno/proprietary/lib64/libcam.iopipe.so:system/lib64/libcam.iopipe.so \
    vendor/bq/zeno/proprietary/lib64/libcam.iopipe_FrmB.so:system/lib64/libcam.iopipe_FrmB.so \
    vendor/bq/zeno/proprietary/lib64/libcam.metadata.so:system/lib64/libcam.metadata.so \
    vendor/bq/zeno/proprietary/lib64/libcam.metadataprovider.so:system/lib64/libcam.metadataprovider.so \
    vendor/bq/zeno/proprietary/lib64/libcam.paramsmgr.so:system/lib64/libcam.paramsmgr.so \
    vendor/bq/zeno/proprietary/lib64/libcam.sdkclient.so:system/lib64/libcam.sdkclient.so \
    vendor/bq/zeno/proprietary/lib64/libcam.utils.so:system/lib64/libcam.utils.so \
    vendor/bq/zeno/proprietary/lib64/libcam1_utils.so:system/lib64/libcam1_utils.so \
    vendor/bq/zeno/proprietary/lib64/libcam3_app.so:system/lib64/libcam3_app.so \
    vendor/bq/zeno/proprietary/lib64/libcam3_hwnode.so:system/lib64/libcam3_hwnode.so \
    vendor/bq/zeno/proprietary/lib64/libcam3_hwpipeline.so:system/lib64/libcam3_hwpipeline.so \
    vendor/bq/zeno/proprietary/lib64/libcam3_pipeline.so:system/lib64/libcam3_pipeline.so \
    vendor/bq/zeno/proprietary/lib64/libcam3_utils.so:system/lib64/libcam3_utils.so \
    vendor/bq/zeno/proprietary/lib64/libcam_hwutils.so:system/lib64/libcam_hwutils.so \
    vendor/bq/zeno/proprietary/lib64/libcam_mmp.so:system/lib64/libcam_mmp.so \
    vendor/bq/zeno/proprietary/lib64/libcam_platform.so:system/lib64/libcam_platform.so \
    vendor/bq/zeno/proprietary/lib64/libcamalgo.so:system/lib64/libcamalgo.so \
    vendor/bq/zeno/proprietary/lib64/libcamdrv.so:system/lib64/libcamdrv.so \
    vendor/bq/zeno/proprietary/lib64/libcamdrv_FrmB.so:system/lib64/libcamdrv_FrmB.so \
    vendor/bq/zeno/proprietary/lib64/libcameracustom.so:system/lib64/libcameracustom.so \
    vendor/bq/zeno/proprietary/lib64/libmtkcamera_client.so:system/lib64/libmtkcamera_client.so \
    vendor/bq/zeno/proprietary/lib64/libtz_uree.so:system/lib64/libtz_uree.so \
    vendor/bq/zeno/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/landmark_group_meta_data.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/landmark_group_meta_data.bin \
    vendor/bq/zeno/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-tree7-wmd.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-tree7-wmd.bin \
    vendor/bq/zeno/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32-tree7-wmd.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32-tree7-wmd.bin \
    vendor/bq/zeno/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-3-tree7-wmd.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-3-tree7-wmd.bin \
    vendor/bq/zeno/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-r0-ri30.4a-v24-tree7-2-wmd.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-r0-ri30.4a-v24-tree7-2-wmd.bin \
    vendor/bq/zeno/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-rn30-ri30.5-v24-tree7-2-wmd.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-rn30-ri30.5-v24-tree7-2-wmd.bin \
    vendor/bq/zeno/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-rp30-ri30.5-v24-tree7-2-wmd.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/head-y0-yi45-p0-pi45-rp30-ri30.5-v24-tree7-2-wmd.bin \
    vendor/bq/zeno/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/pose-r.8.1.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/pose-r.8.1.bin \
    vendor/bq/zeno/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/pose-y-r.8.1.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.7.1/pose-y-r.8.1.bin \
    vendor/bq/zeno/proprietary/vendor/pittpatt/models/recognition/face.face.y0-y0-71-N-tree_7-wmd.bin:system/vendor/pittpatt/models/recognition/face.face.y0-y0-71-N-tree_7-wmd.bin

PRODUCT_PACKAGES += \
    libcam.client \
    libcam_utils \
    libcam.utils.sensorlistener
